posts = [
    {
        'id': 1,
        'author': "Бекжан",
        'title': "О футболе",
        'content': "фцафцафцафцафцафцацафцацфа",
        'date_posted': "19.05.2020",
        'likes': 264,
        'dislikes': 100,
    },
    {
        'id': 2,
        'author': "Адиль",
        'title': "Дети в подвале",
        'content': "Игры в подвале",
        'date_posted': "19.05.2020",
        'likes': 2,
        'dislikes': 1554455,
    },
    {
        'id': 3,
        'author': "Саша",
        'title': "Продаю чатджпт",
        'content': "Дорого",
        'date_posted': "19.05.2024",
        'likes': 100,
        'dislikes': 100,
    },
    {
        'id': 4,
        'author': "Ярослав",
        'title': "Продаю интернет в Шымкенте дешево и качественно",
        'content': "не обманываю",
        'date_posted': "19.04.2016",
        'likes': 12344,
        'dislikes': 1,
    },
    {
        'id': 5,
        'author': "Аян",
        'title': "Я кушать, если что на запись",
        'content': "все понятно (с) Конфуций",
        'date_posted': "19.04.2023",
        'likes': 146,
        'dislikes': 228,
    },
]
